### ISSUE TITLE
Install no longer supported via the Azure Portal

### ISSUE THREAD

**Issue by btm** [chef-partners/azure-chef-extension#292]
Installing the extension is no longer supported through the Azure Portal. We should remove the documentation and replace it with a warning that it is no longer supported.

https://docs.chef.io/azure_portal/

![image](https://user-images.githubusercontent.com/4381/81231436-24f94f00-8fc1-11ea-9d13-dfa8ce836f22.png)

**Comment by btm** [comment]
Internal to Chef context: https://chefio.slack.com/archives/CAF2UDZCN/p1585679386041300

**Comment by Vasu1105** [comment]
We have updated the docs for this so closing it now.

**Comment by dpapkin** [comment]
Please update https://docs.microsoft.com/en-us/azure/developer/chef/client-install-from-azure-portal

Since https://docs.chef.io/azure_portal/ states Install extension no longer supported via azure portal chef/chef-web-docs#2504

My students tried this for several hours and got frustrated

**Comment by dpapkin** [comment]
> Installing the extension is no longer supported through the Azure Portal. We should remove the documentation and replace it with a warning that it is no longer supported.
> 
> https://docs.chef.io/azure_portal/
> 
> ![image](https://user-images.githubusercontent.com/4381/81231436-24f94f00-8fc1-11ea-9d13-dfa8ce836f22.png)

They closed it but did not fix the web page https://docs.microsoft.com/en-us/azure/developer/chef/client-install-from-azure-portal

**Comment by dpapkin** [comment]
> We have updated the docs for this so closing it now.

It has not been uodated, what is your explanation for closing it without updating the webpage?

https://docs.microsoft.com/en-us/azure/developer/chef/client-install-from-azure-portal

Please escalate

**Comment by Vasu1105** [comment]
@dpapkin Thank you for brought that to our notice. We will work on updating that docs on Microsoft.

**Comment by Vasu1105** [comment]
@dpapkin we have took care of updating docs at https://docs.microsoft.com/en-us/azure/developer/chef/client-install-from-azure-portal. So closing it. Thanks.
